# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-08-27 03:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
    ]
